# Generated by Django 3.2 on 2022-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.AddField(
            model_name='package',
            name='full_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.TextField(default='description'),
        ),
    ]
