# Generated by Django 3.2 on 2022-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=80)),
                ('project_description', models.TextField()),
                ('project_image', models.ImageField(blank=True, upload_to='media/')),
                ('project_url', models.URLField(max_length=100)),
                ('project_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
