# Generated by Django 3.2 on 2022-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_language',
            field=models.TextField(default=None),
        ),
    ]
