# Generated by Django 3.2 on 2022-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_package_ordered_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_ordered',
            name='order_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
