# Generated by Django 3.2 on 2022-11-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_package_ordered_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_ordered',
            name='order_tax',
        ),
    ]
