# Generated by Django 3.2 on 2022-11-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_package_ordered_order_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order',
            new_name='package_order',
        ),
    ]
