# Generated by Django 3.2 on 2022-11-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20221121_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_ordered',
            old_name='original_bag',
            new_name='original_cart',
        ),
    ]
