# Generated by Django 3.2 on 2022-11-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_rename_original_bag_package_ordered_original_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_ordered',
            old_name='postal_code',
            new_name='postcode',
        ),
    ]
