# Generated by Django 3.2 on 2022-10-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='status',
        ),
    ]
