# Generated by Django 3.2 on 2022-10-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_remove_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer_password',
        ),
    ]
