# Generated by Django 3.2 on 2022-10-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsribe',
            new_name='Subscribe',
        ),
    ]
